"""initial schema

Revision ID: 40e7b8cf8687
Revises: 
Create Date: 2026-08-27 16:10:18.032112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40e7b8cf8687'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('billing_period', sa.String(length=20), nullable=False),
    sa.Column('features', sa.String(length=1000), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_plans_code'), 'subscription_plans', ['code'], unique=True)
    op.create_index(op.f('ix_subscription_plans_created_at'), 'subscription_plans', ['created_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('USER', 'GUIDE', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('destinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('VISITED', 'PLANNED', 'WISHLIST', name='destinationstatus'), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('visited_from', sa.Date(), nullable=True),
    sa.Column('visited_to', sa.Date(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('hero_image_url', sa.String(length=500), nullable=True),
    sa.Column('google_maps_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_destinations_country'), 'destinations', ['country'], unique=False)
    op.create_index(op.f('ix_destinations_created_at'), 'destinations', ['created_at'], unique=False)
    op.create_index('ix_destinations_lat_lng', 'destinations', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('ix_destinations_latitude'), 'destinations', ['latitude'], unique=False)
    op.create_index(op.f('ix_destinations_longitude'), 'destinations', ['longitude'], unique=False)
    op.create_index(op.f('ix_destinations_name'), 'destinations', ['name'], unique=False)
    op.create_index(op.f('ix_destinations_state'), 'destinations', ['state'], unique=False)
    op.create_index(op.f('ix_destinations_status'), 'destinations', ['status'], unique=False)
    op.create_index(op.f('ix_destinations_user_id'), 'destinations', ['user_id'], unique=False)
    op.create_index('ix_destinations_user_status', 'destinations', ['user_id', 'status'], unique=False)
    op.create_table('guide_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('headline', sa.String(length=150), nullable=False),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('destination_name', sa.String(length=150), nullable=False),
    sa.Column('languages', sa.String(length=200), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('specialization', sa.String(length=150), nullable=True),
    sa.Column('price_per_day', sa.Float(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('rating_avg', sa.Float(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guide_profiles_created_at'), 'guide_profiles', ['created_at'], unique=False)
    op.create_index(op.f('ix_guide_profiles_destination_name'), 'guide_profiles', ['destination_name'], unique=False)
    op.create_index(op.f('ix_guide_profiles_rating_avg'), 'guide_profiles', ['rating_avg'], unique=False)
    op.create_index(op.f('ix_guide_profiles_user_id'), 'guide_profiles', ['user_id'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=300), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_table('photo_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('share_token', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_shares_created_at'), 'photo_shares', ['created_at'], unique=False)
    op.create_index(op.f('ix_photo_shares_share_token'), 'photo_shares', ['share_token'], unique=True)
    op.create_index(op.f('ix_photo_shares_user_id'), 'photo_shares', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash', name='uq_refresh_token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CANCELLED', 'EXPIRED', 'PENDING', name='subscriptionstatus'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('renewal_date', sa.Date(), nullable=True),
    sa.Column('payment_provider_id', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_created_at'), 'subscriptions', ['created_at'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('VISITED', 'PLANNED', 'WISHLIST', name='destinationstatus'), nullable=False),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('drive_folder_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_created_at'), 'trips', ['created_at'], unique=False)
    op.create_index(op.f('ix_trips_end_date'), 'trips', ['end_date'], unique=False)
    op.create_index(op.f('ix_trips_start_date'), 'trips', ['start_date'], unique=False)
    op.create_index(op.f('ix_trips_status'), 'trips', ['status'], unique=False)
    op.create_index('ix_trips_user_dates', 'trips', ['user_id', 'start_date', 'end_date'], unique=False)
    op.create_index(op.f('ix_trips_user_id'), 'trips', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('home_location', sa.String(length=255), nullable=True),
    sa.Column('preferred_travel_style', sa.String(length=50), nullable=True),
    sa.Column('budget_preference', sa.String(length=50), nullable=True),
    sa.Column('favorite_activities', sa.String(length=500), nullable=True),
    sa.Column('trip_duration_preference', sa.String(length=50), nullable=True),
    sa.Column('group_size_preference', sa.String(length=50), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('handle', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_created_at'), 'user_profiles', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_profiles_handle'), 'user_profiles', ['handle'], unique=True)
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.create_table('blogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='generationstatus'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blogs_created_at'), 'blogs', ['created_at'], unique=False)
    op.create_index(op.f('ix_blogs_status'), 'blogs', ['status'], unique=False)
    op.create_index(op.f('ix_blogs_trip_id'), 'blogs', ['trip_id'], unique=False)
    op.create_index(op.f('ix_blogs_user_id'), 'blogs', ['user_id'], unique=False)
    op.create_table('google_drive_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('drive_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_google_drive_links_created_at'), 'google_drive_links', ['created_at'], unique=False)
    op.create_index(op.f('ix_google_drive_links_destination_id'), 'google_drive_links', ['destination_id'], unique=False)
    op.create_index(op.f('ix_google_drive_links_trip_id'), 'google_drive_links', ['trip_id'], unique=False)
    op.create_index(op.f('ix_google_drive_links_user_id'), 'google_drive_links', ['user_id'], unique=False)
    op.create_table('guide_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guide_id', sa.Integer(), nullable=False),
    sa.Column('available_date', sa.Date(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['guide_id'], ['guide_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guide_id', 'available_date', name='uq_guide_availability_date')
    )
    op.create_index(op.f('ix_guide_availability_available_date'), 'guide_availability', ['available_date'], unique=False)
    op.create_index(op.f('ix_guide_availability_guide_id'), 'guide_availability', ['guide_id'], unique=False)
    op.create_table('guide_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('guide_id', sa.Integer(), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('booking_time', sa.String(length=10), nullable=False),
    sa.Column('people_count', sa.Integer(), nullable=False),
    sa.Column('duration_hours', sa.Integer(), nullable=False),
    sa.Column('special_requirements', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELLED', 'COMPLETED', name='bookingstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guide_id'], ['guide_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bookings_guide_status', 'guide_bookings', ['guide_id', 'status'], unique=False)
    op.create_index('ix_bookings_user_status', 'guide_bookings', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_guide_bookings_booking_date'), 'guide_bookings', ['booking_date'], unique=False)
    op.create_index(op.f('ix_guide_bookings_created_at'), 'guide_bookings', ['created_at'], unique=False)
    op.create_index(op.f('ix_guide_bookings_guide_id'), 'guide_bookings', ['guide_id'], unique=False)
    op.create_index(op.f('ix_guide_bookings_status'), 'guide_bookings', ['status'], unique=False)
    op.create_index(op.f('ix_guide_bookings_user_id'), 'guide_bookings', ['user_id'], unique=False)
    op.create_table('memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('memory_date', sa.Date(), nullable=False),
    sa.Column('tags', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memories_created_at'), 'memories', ['created_at'], unique=False)
    op.create_index(op.f('ix_memories_destination_id'), 'memories', ['destination_id'], unique=False)
    op.create_index(op.f('ix_memories_memory_date'), 'memories', ['memory_date'], unique=False)
    op.create_index(op.f('ix_memories_trip_id'), 'memories', ['trip_id'], unique=False)
    op.create_index('ix_memories_user_destination', 'memories', ['user_id', 'destination_id'], unique=False)
    op.create_index(op.f('ix_memories_user_id'), 'memories', ['user_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('provider_payment_id', sa.String(length=150), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_subscription_id'), 'payments', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_table('trip_destinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_destinations_destination_id'), 'trip_destinations', ['destination_id'], unique=False)
    op.create_index(op.f('ix_trip_destinations_trip_id'), 'trip_destinations', ['trip_id'], unique=False)
    op.create_table('trip_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('origin', sa.String(length=150), nullable=False),
    sa.Column('destination_name', sa.String(length=150), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('people', sa.Integer(), nullable=False),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('travel_style', sa.String(length=100), nullable=False),
    sa.Column('interests', sa.String(length=300), nullable=True),
    sa.Column('estimated_budget_min', sa.Float(), nullable=True),
    sa.Column('estimated_budget_max', sa.Float(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('route_description', sa.String(length=300), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='generationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_plans_created_at'), 'trip_plans', ['created_at'], unique=False)
    op.create_index(op.f('ix_trip_plans_trip_id'), 'trip_plans', ['trip_id'], unique=False)
    op.create_index(op.f('ix_trip_plans_user_id'), 'trip_plans', ['user_id'], unique=False)
    op.create_table('blog_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blog_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('heading', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_sections_blog_id'), 'blog_sections', ['blog_id'], unique=False)
    op.create_table('guide_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guide_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['guide_bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guide_id'], ['guide_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id', name='uq_guide_review_booking')
    )
    op.create_index(op.f('ix_guide_reviews_created_at'), 'guide_reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_guide_reviews_guide_id'), 'guide_reviews', ['guide_id'], unique=False)
    op.create_index('ix_guide_reviews_guide_rating', 'guide_reviews', ['guide_id', 'rating'], unique=False)
    op.create_index(op.f('ix_guide_reviews_user_id'), 'guide_reviews', ['user_id'], unique=False)
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.Column('memory_id', sa.Integer(), nullable=True),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('caption', sa.String(length=300), nullable=True),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['memory_id'], ['memories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photos_created_at'), 'photos', ['created_at'], unique=False)
    op.create_index(op.f('ix_photos_destination_id'), 'photos', ['destination_id'], unique=False)
    op.create_index(op.f('ix_photos_memory_id'), 'photos', ['memory_id'], unique=False)
    op.create_index('ix_photos_user_destination', 'photos', ['user_id', 'destination_id'], unique=False)
    op.create_index(op.f('ix_photos_user_id'), 'photos', ['user_id'], unique=False)
    op.create_table('trip_plan_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_plan_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['trip_plan_id'], ['trip_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_plan_days_trip_plan_id'), 'trip_plan_days', ['trip_plan_id'], unique=False)
    op.create_table('photo_share_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_share_id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['photo_share_id'], ['photo_shares.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_share_items_photo_id'), 'photo_share_items', ['photo_id'], unique=False)
    op.create_index(op.f('ix_photo_share_items_photo_share_id'), 'photo_share_items', ['photo_share_id'], unique=False)
    op.create_table('trip_plan_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_plan_day_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trip_plan_day_id'], ['trip_plan_days.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_plan_activities_trip_plan_day_id'), 'trip_plan_activities', ['trip_plan_day_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_plan_activities_trip_plan_day_id'), table_name='trip_plan_activities')
    op.drop_table('trip_plan_activities')
    op.drop_index(op.f('ix_photo_share_items_photo_share_id'), table_name='photo_share_items')
    op.drop_index(op.f('ix_photo_share_items_photo_id'), table_name='photo_share_items')
    op.drop_table('photo_share_items')
    op.drop_index(op.f('ix_trip_plan_days_trip_plan_id'), table_name='trip_plan_days')
    op.drop_table('trip_plan_days')
    op.drop_index(op.f('ix_photos_user_id'), table_name='photos')
    op.drop_index('ix_photos_user_destination', table_name='photos')
    op.drop_index(op.f('ix_photos_memory_id'), table_name='photos')
    op.drop_index(op.f('ix_photos_destination_id'), table_name='photos')
    op.drop_index(op.f('ix_photos_created_at'), table_name='photos')
    op.drop_table('photos')
    op.drop_index(op.f('ix_guide_reviews_user_id'), table_name='guide_reviews')
    op.drop_index('ix_guide_reviews_guide_rating', table_name='guide_reviews')
    op.drop_index(op.f('ix_guide_reviews_guide_id'), table_name='guide_reviews')
    op.drop_index(op.f('ix_guide_reviews_created_at'), table_name='guide_reviews')
    op.drop_table('guide_reviews')
    op.drop_index(op.f('ix_blog_sections_blog_id'), table_name='blog_sections')
    op.drop_table('blog_sections')
    op.drop_index(op.f('ix_trip_plans_user_id'), table_name='trip_plans')
    op.drop_index(op.f('ix_trip_plans_trip_id'), table_name='trip_plans')
    op.drop_index(op.f('ix_trip_plans_created_at'), table_name='trip_plans')
    op.drop_table('trip_plans')
    op.drop_index(op.f('ix_trip_destinations_trip_id'), table_name='trip_destinations')
    op.drop_index(op.f('ix_trip_destinations_destination_id'), table_name='trip_destinations')
    op.drop_table('trip_destinations')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_subscription_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_memories_user_id'), table_name='memories')
    op.drop_index('ix_memories_user_destination', table_name='memories')
    op.drop_index(op.f('ix_memories_trip_id'), table_name='memories')
    op.drop_index(op.f('ix_memories_memory_date'), table_name='memories')
    op.drop_index(op.f('ix_memories_destination_id'), table_name='memories')
    op.drop_index(op.f('ix_memories_created_at'), table_name='memories')
    op.drop_table('memories')
    op.drop_index(op.f('ix_guide_bookings_user_id'), table_name='guide_bookings')
    op.drop_index(op.f('ix_guide_bookings_status'), table_name='guide_bookings')
    op.drop_index(op.f('ix_guide_bookings_guide_id'), table_name='guide_bookings')
    op.drop_index(op.f('ix_guide_bookings_created_at'), table_name='guide_bookings')
    op.drop_index(op.f('ix_guide_bookings_booking_date'), table_name='guide_bookings')
    op.drop_index('ix_bookings_user_status', table_name='guide_bookings')
    op.drop_index('ix_bookings_guide_status', table_name='guide_bookings')
    op.drop_table('guide_bookings')
    op.drop_index(op.f('ix_guide_availability_guide_id'), table_name='guide_availability')
    op.drop_index(op.f('ix_guide_availability_available_date'), table_name='guide_availability')
    op.drop_table('guide_availability')
    op.drop_index(op.f('ix_google_drive_links_user_id'), table_name='google_drive_links')
    op.drop_index(op.f('ix_google_drive_links_trip_id'), table_name='google_drive_links')
    op.drop_index(op.f('ix_google_drive_links_destination_id'), table_name='google_drive_links')
    op.drop_index(op.f('ix_google_drive_links_created_at'), table_name='google_drive_links')
    op.drop_table('google_drive_links')
    op.drop_index(op.f('ix_blogs_user_id'), table_name='blogs')
    op.drop_index(op.f('ix_blogs_trip_id'), table_name='blogs')
    op.drop_index(op.f('ix_blogs_status'), table_name='blogs')
    op.drop_index(op.f('ix_blogs_created_at'), table_name='blogs')
    op.drop_table('blogs')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_handle'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_created_at'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_trips_user_id'), table_name='trips')
    op.drop_index('ix_trips_user_dates', table_name='trips')
    op.drop_index(op.f('ix_trips_status'), table_name='trips')
    op.drop_index(op.f('ix_trips_start_date'), table_name='trips')
    op.drop_index(op.f('ix_trips_end_date'), table_name='trips')
    op.drop_index(op.f('ix_trips_created_at'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_created_at'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_photo_shares_user_id'), table_name='photo_shares')
    op.drop_index(op.f('ix_photo_shares_share_token'), table_name='photo_shares')
    op.drop_index(op.f('ix_photo_shares_created_at'), table_name='photo_shares')
    op.drop_table('photo_shares')
    op.drop_index('ix_notifications_user_read', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_guide_profiles_user_id'), table_name='guide_profiles')
    op.drop_index(op.f('ix_guide_profiles_rating_avg'), table_name='guide_profiles')
    op.drop_index(op.f('ix_guide_profiles_destination_name'), table_name='guide_profiles')
    op.drop_index(op.f('ix_guide_profiles_created_at'), table_name='guide_profiles')
    op.drop_table('guide_profiles')
    op.drop_index('ix_destinations_user_status', table_name='destinations')
    op.drop_index(op.f('ix_destinations_user_id'), table_name='destinations')
    op.drop_index(op.f('ix_destinations_status'), table_name='destinations')
    op.drop_index(op.f('ix_destinations_state'), table_name='destinations')
    op.drop_index(op.f('ix_destinations_name'), table_name='destinations')
    op.drop_index(op.f('ix_destinations_longitude'), table_name='destinations')
    op.drop_index(op.f('ix_destinations_latitude'), table_name='destinations')
    op.drop_index('ix_destinations_lat_lng', table_name='destinations')
    op.drop_index(op.f('ix_destinations_created_at'), table_name='destinations')
    op.drop_index(op.f('ix_destinations_country'), table_name='destinations')
    op.drop_table('destinations')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_subscription_plans_created_at'), table_name='subscription_plans')
    op.drop_index(op.f('ix_subscription_plans_code'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    # ### end Alembic commands ###
