"""photo animations

Revision ID: 58f121ba01dd
Revises: 5cf8d01e55ef
Create Date: 2026-08-29 21:25:01.080628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58f121ba01dd'
down_revision: Union[str, Sequence[str], None] = '5cf8d01e55ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo_animations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='generationstatus'), nullable=False),
    sa.Column('output_url', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_animations_created_at'), 'photo_animations', ['created_at'], unique=False)
    op.create_index(op.f('ix_photo_animations_status'), 'photo_animations', ['status'], unique=False)
    op.create_index('ix_photo_animations_user', 'photo_animations', ['user_id'], unique=False)
    op.create_index(op.f('ix_photo_animations_user_id'), 'photo_animations', ['user_id'], unique=False)
    op.create_table('photo_animation_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_animation_id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['photo_animation_id'], ['photo_animations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_animation_items_photo_animation_id'), 'photo_animation_items', ['photo_animation_id'], unique=False)
    op.create_index(op.f('ix_photo_animation_items_photo_id'), 'photo_animation_items', ['photo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photo_animation_items_photo_id'), table_name='photo_animation_items')
    op.drop_index(op.f('ix_photo_animation_items_photo_animation_id'), table_name='photo_animation_items')
    op.drop_table('photo_animation_items')
    op.drop_index(op.f('ix_photo_animations_user_id'), table_name='photo_animations')
    op.drop_index('ix_photo_animations_user', table_name='photo_animations')
    op.drop_index(op.f('ix_photo_animations_status'), table_name='photo_animations')
    op.drop_index(op.f('ix_photo_animations_created_at'), table_name='photo_animations')
    op.drop_table('photo_animations')
    # ### end Alembic commands ###
