"""trip collaborators

Revision ID: 5cf8d01e55ef
Revises: 61bd14005438
Create Date: 2026-08-29 21:18:42.768164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cf8d01e55ef'
down_revision: Union[str, Sequence[str], None] = '61bd14005438'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_collaborators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('invited_email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('EDITOR', 'VIEWER', name='collaboratorrole'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', name='collaboratorstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_collaborators_created_at'), 'trip_collaborators', ['created_at'], unique=False)
    op.create_index(op.f('ix_trip_collaborators_trip_id'), 'trip_collaborators', ['trip_id'], unique=False)
    op.create_index('ix_trip_collaborators_trip_user', 'trip_collaborators', ['trip_id', 'user_id'], unique=True)
    op.create_index(op.f('ix_trip_collaborators_user_id'), 'trip_collaborators', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_collaborators_user_id'), table_name='trip_collaborators')
    op.drop_index('ix_trip_collaborators_trip_user', table_name='trip_collaborators')
    op.drop_index(op.f('ix_trip_collaborators_trip_id'), table_name='trip_collaborators')
    op.drop_index(op.f('ix_trip_collaborators_created_at'), table_name='trip_collaborators')
    op.drop_table('trip_collaborators')
    # ### end Alembic commands ###
