"""trip expenses and participants

Revision ID: 61bd14005438
Revises: 40e7b8cf8687
Create Date: 2026-08-27 17:39:58.001595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61bd14005438'
down_revision: Union[str, Sequence[str], None] = '40e7b8cf8687'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_participants_created_at'), 'trip_participants', ['created_at'], unique=False)
    op.create_index('ix_trip_participants_trip', 'trip_participants', ['trip_id'], unique=False)
    op.create_index(op.f('ix_trip_participants_trip_id'), 'trip_participants', ['trip_id'], unique=False)
    op.create_table('trip_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('paid_by_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['paid_by_id'], ['trip_participants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_expenses_created_at'), 'trip_expenses', ['created_at'], unique=False)
    op.create_index('ix_trip_expenses_trip', 'trip_expenses', ['trip_id'], unique=False)
    op.create_index(op.f('ix_trip_expenses_trip_id'), 'trip_expenses', ['trip_id'], unique=False)
    op.create_table('trip_expense_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('share_amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['trip_expenses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['trip_participants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_expense_shares_expense_id'), 'trip_expense_shares', ['expense_id'], unique=False)
    op.create_index(op.f('ix_trip_expense_shares_participant_id'), 'trip_expense_shares', ['participant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_expense_shares_participant_id'), table_name='trip_expense_shares')
    op.drop_index(op.f('ix_trip_expense_shares_expense_id'), table_name='trip_expense_shares')
    op.drop_table('trip_expense_shares')
    op.drop_index(op.f('ix_trip_expenses_trip_id'), table_name='trip_expenses')
    op.drop_index('ix_trip_expenses_trip', table_name='trip_expenses')
    op.drop_index(op.f('ix_trip_expenses_created_at'), table_name='trip_expenses')
    op.drop_table('trip_expenses')
    op.drop_index(op.f('ix_trip_participants_trip_id'), table_name='trip_participants')
    op.drop_index('ix_trip_participants_trip', table_name='trip_participants')
    op.drop_index(op.f('ix_trip_participants_created_at'), table_name='trip_participants')
    op.drop_table('trip_participants')
    # ### end Alembic commands ###
